sudo: true
matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    language: node_js
    node_js:
    - node
    - 9
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    services: docker
    language: node_js
    node_js:
    - node
    - 9
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-multilib
        - g++-4.8
        - g++-multilib
        - icnsutils
        - graphicsmagick
        - xz-utils
        - xorriso
        - rpm
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
cache:
  yarn: true
  directories:
  - node_modules
  - app/node_modules
  - "$(npm config get prefix)/lib/node_modules"
  - flow-typed
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/docker"
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-4.8"; fi
install:
- yarn
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    /sbin/start-stop-daemon \
    --start \
    --quiet \
    --pidfile /tmp/custom_xvfb_99.pid \
    --make-pidfile \
    --background \
    --exec /usr/bin/Xvfb \
    -- :99 -ac -screen 0 1280x1024x16
  else
    :
  fi
before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: 'docs'
  on:
    branch: master
script:
- yarn package-ci
- yarn lint
- yarn test
- yarn build-e2e
env:
  global:
    secure: k6wF1RoAf5girqS+LFju9qu9qC4HY14y+zuwQrByEiI83L16y0IMrtBsq9hN1PjOTb3XtwWG1Ar23L6M7PGRjFv3dJKNDQqS6EsPPY3dqAKOBxpT8WvIF0ggp9MuL9/6XWCK/QJuN1SyTYarBGVw1NZIFfsECyzuP+h9Cxj0p1Q7/dnQwLMO605WqCqaxO989/LDvYitgnp93zknYruWpZbbGPZfe2151U5bsNwVjh9U2Fc7S+GYJuh9XxdP8yVBEA/0N0E95a93GkLgtAZJRAvEPM+QpOB7D2yGcNns5lbo3vfuDJ2wKTivNE7YQuWonjq5NJLqXqvOJvThphB0s30w+mIDo16GNpYtb067/AjNnyh6ZoswI//rzlhupWlgvEGA3jX3tgM2n3TZ+VpuLjOYFa+tLQKCQ7gkxD6vklm3t5asbKwvosIGKhsYzI7vMLlJqhENi6E60dElk+ZYDC8FIuxBpSNe4N3OUG/WE5Wzwv/+IUJ1bXFjQCg2Ii84EUEegB2kY3j9ZROVyTClcvyaVvHalJlJtfcxZZcDiCjRhfPxeJ8UDpcVQUOBi3vLWR4XpKmNIf1iWX9hPkE2MtG/kVT8Sr7VH6c7OOm6eCaLOupJdLnuCn3WsRFWHMo1C+MxIuUeso5OOCLUQUPl5YbsYQsj3Hrz90crB9J+2xk=
